INSERT INTO rating_MPA (name)
SELECT 'G'
WHERE NOT EXISTS (
    SELECT 1 FROM rating_MPA WHERE NAME = 'G'
);
INSERT INTO rating_MPA (name)
SELECT 'PG'
WHERE NOT EXISTS (
    SELECT 1 FROM rating_MPA WHERE NAME = 'PG'
);
INSERT INTO rating_MPA (name)
SELECT 'PG-13'
WHERE NOT EXISTS (
    SELECT 1 FROM rating_MPA WHERE NAME = 'PG-13'
);
INSERT INTO rating_MPA (name)
SELECT 'R'
WHERE NOT EXISTS (
    SELECT 1 FROM rating_MPA WHERE NAME = 'R'
);
INSERT INTO rating_MPA (name)
SELECT 'NC-17'
WHERE NOT EXISTS (
    SELECT 1 FROM rating_MPA WHERE NAME = 'NC-17'
);

INSERT INTO GENRES (name)
SELECT 'Комедия'
WHERE NOT EXISTS (
    SELECT 1 FROM GENRES WHERE NAME = 'Комедия'
);
INSERT INTO GENRES (name)
SELECT 'Драма'
WHERE NOT EXISTS (
    SELECT 1 FROM GENRES WHERE NAME = 'Драма'
);
INSERT INTO GENRES (name)
SELECT 'Мультфильм'
WHERE NOT EXISTS (
    SELECT 1 FROM GENRES WHERE NAME = 'Мультфильм'
);
INSERT INTO GENRES (name)
SELECT 'Триллер'
WHERE NOT EXISTS (
    SELECT 1 FROM GENRES WHERE NAME = 'Триллер'
);
INSERT INTO GENRES (name)
SELECT 'Документальный'
WHERE NOT EXISTS (
    SELECT 1 FROM GENRES WHERE NAME = 'Документальный'
);
INSERT INTO GENRES (name)
SELECT 'Боевик'
WHERE NOT EXISTS (
    SELECT 1 FROM GENRES WHERE NAME = 'Боевик'
);